name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  rust-macos-aarch64:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
          components: rustfmt, clippy

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo check
        run: cargo check --all-targets --target aarch64-apple-darwin

      - name: Cargo test
        run: cargo test --doc --target aarch64-apple-darwin

      - name: Cargo clippy
        run: cargo clippy --all-targets --target aarch64-apple-darwin -- -D warnings

  rust-linux-x86_64:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
          components: rustfmt, clippy

      - name: Cargo check
        run: cargo check --all-targets --target x86_64-unknown-linux-gnu

      - name: Cargo test
        run: cargo test --doc --target x86_64-unknown-linux-gnu

      - name: Cargo clippy
        run: cargo clippy --all-targets --target x86_64-unknown-linux-gnu -- -D warnings

  rust-linux-aarch64-check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Cargo check (lib only)
        run: cargo check --lib --target aarch64-unknown-linux-gnu
